apiVersion: v1
kind: Service
metadata:
  namespace: twitter
  name: twitter-node-api-svc
spec:
  type: ClusterIP
  #type: LoadBalancer
  #type: NodePort
  selector:
    app: twitter-node-api
  ports:
    - protocol: TCP
      port: 3000
